### ISSUE TITLE
How do you do a preview deploy?

### ISSUE THREAD

**Issue by NullVoxPopuli** [netlify/netlify-cli#44]
only seeing this in the deploy help:
```
 $ netlify deploy --help

  Usage: deploy [options]

  Push a new deploy to netlify

  Options:

    -h, --help         output usage information
    -s --site-id [id]  Deploy to site with <id>
    -p --path [path]   Path to a folder or zip file to deploy
    -d --draft         Deploy as a draft without publishing
```

I'm wanting to script the deploy so I can avoid using netlify's build tools 
![image](https://user-images.githubusercontent.com/199018/42141873-15cc5cb2-7d7a-11e8-818d-018ff0f8f611.png)

(I'm using gitlab and have a pretty slick setup so far)

my current production deploy script is:
```bash
      BRANCH=$(git rev-parse --abbrev-ref HEAD)

      if [[ "$BRANCH" == "master" ]]; then
        time ./run yarn build:production
        time npm i -g netlify-cli
        time netlify deploy -s emberclear -p packages/frontend/dist -t $NETLIFY_ACCESS_TOKEN -e production
      fi
```

was hoping to be able to do something for branches / previews as well.

thanks!

**Comment by fool** [comment]
This repo and software is deprecated @NullVoxPopuli .  However I can still answer your question.

There is no way to do a branch or preview deploy from the CLI.  Only production (published) and draft (not published, can be published later if you want) are supported from the command line.

Our concept of deploy previews and branch deploys REQUIRE git, since they are about branches and PR's and we must build them to classify them as such.

cc @bcomnes and @DavidWells as you think about the next CLI this is a feature request I've heard before.

**Comment by NullVoxPopuli** [comment]
If this tool is deprecated, what's the recommended way to deploy from a ci environment?

**Comment by fool** [comment]
[netlifyctl](https://github.com/netlify/netlifyctl)

**Comment by kirillgroshkov** [comment]
Related: https://github.com/netlify/cli/issues/275

**Comment by GeorgeTaveras1231** [comment]
@fool I understand your comment is old but it was a bit confusing to find that that repo claims to be deprecated and redirects users back to this repo. It's probably a good idea to update your comment  to reflect that change to avoid any further confusion.

**Comment by fool** [comment]
I think you figured it out ok :) 

but I updated the comment anyway per your suggestion.
